### ISSUE TITLE
How to export json data to excel with a hyperlink field?

### ISSUE THREAD

**Issue by leoyb** [jecovier/vue-json-excel#130]

**Comment by jecovier** [comment]
Hi there, sorry for the late response. I don't quite get your question, but you can customize the default slot to render any html element. The root node it's a div with a @click event attach to it, so you can put something like this:
```html
<vue-json-excel>
    <a href="#">your text</a>
</vue-json-excel>
```
It won't behave like a normal hyperlink because the click event will be hijacked by the div. But it will look like a regular hyperlink, though.
