### ISSUE TITLE
doesn't work in Edge

### ISSUE THREAD

**Issue by ryatziv** [jecovier/vue-json-excel#24]
Clicking doesn't work in edge...

**Comment by DrLongGhost** [comment]
I messed around with this for 30 minutes or so and couldn't fix it in Edge. It seems like the code is correct and should work but I can confirm it doesn't.

I'm a little skeptical about the code quality for this project since the formatting is a bit of mess and in addition to all the other open issues, I just noticed in the download function there's some dead code:  

if (alink.download === '') {  // "alink" is not defined anywhere

For me, no Edge support is a deal breaker. Since all I need is CSV support, it looks like I can just write my own CSV generation code and use this project to create the download link:  https://github.com/rndme/download

I verified that that project does work in Edge but wasn't able to use it to help fix this one.

**Comment by ryatziv** [comment]
I've been trying to get edge to work all day.  I can get it to download now, but it also navigates away to the root of the application for some reason.  I agree with you about the quality of the project... seems that the basics are still missing.

`https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/html5/file-api/blob`

**Comment by ryatziv** [comment]
Just figured out why it navigates away in Edge.  Change the `<a href` and it's fixed.

**Comment by ryatziv** [comment]
@DrLongGhost before you write your own CSV generation code check out papaparse.  Thanks for introducing me to downloadjs.

This is what I ended up doing:

```
downloadCsv (fields, data, name) {
      let cvsData = Papa.unparse({fields: fields, data: data})
      download(cvsData, name, 'application/csv')
    },
```

**Comment by DrLongGhost** [comment]
I've worked with PapaParse before and it's great for malformed data.

My particular use case right now is I have a Vue site that needs to prompt download of a CSV built from the JSON-based API powering the site. Since I want to keep things light, I prefer to avoid libraries with lots of dependencies -- both to keep bundle file size down and to avoid packaging complications.

For this reason, I'm most likely going to use downloadjs only and write the Vue stuff and JSON -> CSV code myself. Since I control and trust the API, I don't need to support malformed JSON and the other JSON -> CSV converters, including PapaParse, are too heavy for what I need. (That said, PapaParse at least has no dependencies so that's nice)

I'm not sure where the author of "vue-json-excel" wants to take the library but there's definitely something to be said for keeping things simple and avoiding tons of dependencies. OTOH, things also need to work well in almost all circumstances...

**Comment by jecovier** [comment]
@DrLongGhost @ryatziv I didn't realize how messy the code was, I clean the code now. @ryatziv Thanks for your solution, downloadjs it's a really good library. @DrLongGhost I really want this library to be as simple as possible and I hope keep in that way. Thank you both for the good critic!
