### ISSUE TITLE
Cell based customization of excel sheet for showing multiple content before or after the table

### ISSUE THREAD

**Issue by ni8mr** [jecovier/vue-json-excel#58]
Currently we can add only **title** (multiple or single). It would be better if we can customize our excel sheet further more. Add more headers (assigning them to the different cells), or some customized footers etc.

**Comment by jecovier** [comment]
Hi @ni8mr this is a really good feature request, sadly right now there are some limitations in the way that the component can export the data. I use some browser options to export the files without using a bulk library in order to keep this component as little as possible. However, I implement the footer feature in this update and works exactly like the header attribute, just use the footer prop. If you need a more robust solution to customize the output, you can use some other alternatives like https://github.com/clarketm/js-xlsx or this jquery plugin https://tableexport.v3.travismclarke.com/. Hope this would be useful for you and thanks for the suggestion.
