### ISSUE TITLE
fields variable is conflicting with other plugins probably vue validation module

### ISSUE THREAD

**Issue by fosterz** [jecovier/vue-json-excel#78]
[Vue warn]: The computed property "fields" is already defined as a prop.

**Comment by Bobur-kobilov** [comment]
I have the same problem. Could you solve it?

**Comment by rosman21** [comment]
following also having the same issue...

**Comment by jecovier** [comment]
Hello guys, this issue is solved using the export-fields prop. Please read the "documentation" in the read me file for more details.


export-fields (exportFields) | Object | this prop is used to fix the problem with other components that use  the variable fields, like vee-validate. exportFields works exactly like  fields
-- | -- | --

**Comment by salvationarinze** [comment]
Still shows the warning even after using `export-fields`
